version: '3'
services:
  freqtrade:
    build: .
    # image: freqtradeorg/freqtrade:develop
    restart: unless-stopped
    container_name: freqtrade
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Default command, can be overridden
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
